# .github/workflows/deploy.yml
name: Deploy documentation to github pages

# Define when to run action
on:
  # run action on push to main bhranch
  push:
    branches: [ main ]
  
  # run also this workflow manually when needed
  workflow_dispatch:

# github token permissions are set here
permissions:
  contents: read
  pages: write
  id-token: write

# deployment concurrency set to one
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout docusaurus repository
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install deps
        run: npm i

      - name: Build docs
        run: npm run build

      - name: Run gh action to setup pages
        uses: actions/configure-pages@v3

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Run gh action to deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
